version: '3.9'

services:
  web:
    container_name: growthhackers_web
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: yarn dev
    volumes:
      - ./packages/web:/app
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - app
  
  server:
    container_name: growthhackers_server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: yarn start:dev
    volumes:
      - ./packages/server:/app
    env_file:
      - ./packages/server/.env
    ports:
      - "4000:4000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: growthhackers_db
    image: postgres
    restart: unless-stopped
    volumes:
      - './.data/db:/var/lib/postgresql/data'
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - ./packages/server/.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGUSER=${DB_USERNAME}
      - PGPASSWORD=${DB_PASSWORD}
      - PGDATABASE=${DB_DATABASE}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - app

networks:
  app:
    driver: bridge
