version: '3.9'

services:
  web:
    container_name: growthhackers_web
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
    command: yarn dev
    volumes:
      - ./packages/web:/app
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - app

networks:
  app:
    driver: bridge
